title: Lumu.info
description: A website about a Paolumu with too much free time
baseurl: "/"
domain: "lumu.info"
url: "https://www.lumu.info"

github_username: paolumaya

# markdown: obsidian-parser
# markdown: kramdown
markdown: ObsidianConverter
# kramdown:
#     parse_block_html: true

plugins:
    - ObsidianConverter
    - jekyll-sitemap
    - obsidian_links

# plugins_dir:
    # - _plugins

theme: minima
minima:
  - skin: dark
# remote_theme:
# remote_theme: b2a3e8/jekyll-theme-console

exclude:
    - flake.lock
    - Gemfile*
    - flake*
    - gemset.nix
    - post_ideas
    - serve.sh
    - LICENSE
    - notes
    - .git
    - .gitignore

defaults:
    - scope:
          path: "assets"
      values:
          sitemap: false
