title: Lumu.info
description: A website about a Paolumu with too much free time
baseurl: ""
domain: "lumu.info"
url: "https://lumu.info"

github_username: paolumaya

markdown: kramdown
kramdown:
    parse_block_html: true

theme: jekyll-theme-hacker

exclude:
    - flake.lock
    - Gemfile*
    - flake*
    - gemset.nix
    - post_ideas
    - serve.sh
    - LICENSE
    - notes
