title: Lumu.info
description: A website about a Paolumu with too much free time
baseurl: "https://www.lumu.info"
domain: "lumu.info"
url: "https://www.lumu.info"

github_username: paolumaya

markdown: kramdown
kramdown:
    parse_block_html: true

# theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console

plugins:
    - jekyll-sitemap
    # - jekyll-obsidian

exclude:
    - flake.lock
    - Gemfile*
    - flake*
    - gemset.nix
    - post_ideas
    - serve.sh
    - LICENSE
    - notes
    - .git
    - .gitignore

defaults:
    - scope:
          path: "assets"
      values:
          sitemap: false
