title: Lumu.info
description: A website about a Paolumu with too much free time
baseurl: "/"
domain: "lumu.info"
url: "https://www.lumu.info"

github_username: paolumaya

markdown: kramdown
kramdown:
    parse_block_html: true

plugins:
    - jekyll-sitemap

plugins_dir:
    - _plugins

# theme: minima
# minima:
#     - skin: dark
# remote_theme:
remote_theme: b2a3e8/jekyll-theme-console

exclude:
    - flake.lock
    - Gemfile*
    - flake*
    - gemset.nix
    - post_ideas
    - serve.sh
    - LICENSE
    - notes
    - .git
    - .gitignore
    - _lore/.obsidian
    - _lore/.stfolder
    - _lore/Inspiration
    - _lore/Templates
    - _lore/.gitignore
    - _lore/README.md
    - .github
    - .jekyll-cache
    - .bundle
    - README.md

defaults:
    - scope:
          path: "assets"
      values:
          sitemap: false

collections:
  lore:
    output: true
    permalink: /lore/:path/