# This file is autogenerated by the flake.nix file, do not edit
source "https://rubygems.org"

# Gems dependencies to be installed
gem "jekyll-theme-console", "~> 0.3.12"
gem "minima", "~> 2.5.1"
gem "webrick", "~> 1.9.1"
gem "github-pages", "~> 232", group: :jekyll_plugins

# Github Pages plugins
group :jekyll_plugins do
  gem "jekyll-sitemap", "~> 1.4.0"
end

