name: Deploy Quartz Site

on:
  push:
    branches:
      - v4
  workflow_dispatch:

permissions: 
  contents: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # submodules: false

      - name: Pull submodules
        run: git submodule update --init
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm install
        
      - name: Build Quartz
        run: npx quartz build

      - name: add CNAME
        run: echo www.lumu.info > public/CNAME
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './public'
          publish_branch: 'gh_pages'